name: Docker Image CI

on:
  push:
    branches: [ '*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${GITHUB_REPOSITORY,,}:${{ github.sha }}
      
    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${GITHUB_REPOSITORY,,}:${{ github.sha }}
        tags: ${GITHUB_REPOSITORY,,}:${{ github.sha }}
        registry: quay.io/quay-user
        username: portnumber53
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
